"""add marketer_id to commission

Revision ID: c63ad28faadb
Revises: 7df3e8ba18db
Create Date: 2026-04-03 20:24:07.790202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63ad28faadb'
down_revision = '7df3e8ba18db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'marketer', ['marketer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('marketer_id')

    # ### end Alembic commands ###
